exports.data = {
    happy: {
        teens: [
            "Great spirit you have today, how did that happen?",
            "Have you seen any good movies lately?",
            "You’re looking great! What you’re up to for the next weekend?",
            "What’s your go-to comfort food?",
            "What was the best part of your day today?",
            "What bands are you listening to these days?",
            "If you could magically become fluent in any language, what would it be?",
            "Which shows are you watching right now?",
            "What is the craziest thing one of your teachers has done?",
            "If you were famous, what would you be famous for?",
            "What is your cellphone wallpaper?",
            "What was the funniest thing that happened to you lately?",
            "Would you rather live without heat and AC or live without social media?",
        ],
        adults: [
            "What would you name your boat if you had one?",
            "What will finally break the internet?",
            "What are some things that sound like compliments but are actually insults?",
            "What’s your biggest screw up in the kitchen?",
            "What’s the closest thing to real magic?",
            "What would you fill a free one-minute ad slot during the Super Bowl with?",
            // "What quote or saying do people spout but are complete BS?",
            "Are you a morning person or a night person?",
            "Where is the line between insanity and creativity?",
            "Isn’t one person’s terrorist another person’s freedom fighter?",
            "How would your friends describe you?",
            "What is love?",
            "What is the color of your best friends eyes?",
        ],
        seniors: [
            "What fashion trend would you like to bring back?",
            "If you could change places with anyone in the world, who would it be and why?",
            "What big world events were the most memorable while you were growing up?",
            "What life advice would you pass along to your grandchildren?",
            "Did you have a nickname growing up?",
        ]
    },
    neutral: {
        teens: [
            "Do you feel like a responsible young adult?",
            "Do you have any brothers or sisters?",
            "If you had to teach a class on one thing, what would you teach ?",
            "Do you have a role model?",
            "How did you feel while taking your driver’s license test?",
            "Do you think millennials are really that different from other generations?",
            // "Have your parents ever embarrassed you?",
            // "What do you do and think when you see a homeless person?",
            "What is the best and worst food that your school cafeteria serves?",
            "What are the best and worst things about having a smartphone?",
            // "How many kids do you think you might want some day?",
            "Are you more of a dog or cat person?",
            "How tall would you like to be, if you could choose?",
            "Do you have a celebrity crush?",
            "What’s the worst commercial you’ve recently seen?",
            "What’s the most useless talent you have?",
            "If lying is wrong, are white lies okay?",
        ],
        adults: [
            "Is a family still relevant in the modern world?",
            // "How did you and your spouse meet?",
            "How are you?",
        ],
        seniors: [
            "What happens after we die?",
            "What do people strive for after enlightenment?",
            "What are you the most proud of in your life?",
            "How are you?",
        ]
    },
    sad: {
        teens: [
            "How was your day at school??",
            "What's the best thing that's happened to you this year?",
            "What’s your favorite series?",
            "When was the last time you said hi to your cousins?",
            "If you could only eat one thing for the rest of your life, what would it be?",
            "Do you feel like you ever procrastinate?",
            "What were some of the birthday presents you ever received?",
            // "If money cannot buy happiness, can you ever be truly happy with no money?",
        ],
        adults: [
            // "Do you know anyone who you would say has an ideal marriage or relationship?",
            "What is your dream job and do you believe you will ever succeed at having it?",
            // "Is it better to love and lose or never to love?",
            "How are you?",
        ],
        seniors: [
            "What are some lessons you learned over the course of your life?",
            // "Some people say that they have had difficult or stressful experiences but they have learned important lessons from them. Is that true for you? Can you give examples of what you learned?",
            // "As you look back over your life, do you see any 'turning points'; that is, a key event or experience that changed over the course of your life or set you on a different track?",
            // "What’s the secret to a happy marriage?",
            "What are some of the important choices or decisions you made that you have learned from?",
            "What would you say you know now about living a happy and successful life that you didn’t know when you were twenty?",
            "What would you say are the major values that you live by?",
            "What is the chance that two people in a room have the same birthday?"
        ]
    }
}
